apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::486805173260:role/eksctl-eksclt-demo-nodegroup-ng-6-NodeInstanceRole-13B03CPQTC96D
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
        rolearn: arn:aws:iam::486805173260:role/UdacityFlaskDeployCBKubectlRole
        username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-29T20:02:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "45643"
  uid: 6670937d-48c3-4f90-a48d-bc596ab105b7
