apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::486805173260:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-KGDSHAZXWJM7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::486805173260:role/udacityFSNDProject4
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-01T20:10:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1783"
  uid: a81923be-aff9-4e3a-aadd-f9ca885bcb87
